language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - yarn
script:
  - yarn test
after_success:
  - yarn run coveralls
  - "stable"
notifications:
  email: false
  slack: true
