language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - yarn
script:
  - yarn test
after_success:
  - yarn run coveralls
  - 'stable'
notifications:
  email: false
  slack: andela:LX8VPRMaSP4tskr94puPVmFf
